platform :ios, '13.0'

#source 'ssh://git@us003.fly-access.com:7999/msdk/ios-internal-cocoapods-specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'DSS-APP' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '4.13'
  pod 'DJI-UXSDK-iOS', '4.13'
  pod 'DJIWidget', '~> 1.6.3'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
  pod 'SwiftyZeroMQ'
  pod 'SwiftyJSON'
end
